# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-21 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(to='client.Hashtag'),
        ),
    ]
