# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-24 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_article_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(related_name='articles', to='client.Hashtag'),
        ),
    ]
